name: tank_battle_city
description: "A new Flutter project."
version: 0.2.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^10.1.0
  flutter_bloc: ^9.1.1
  get_it: ^7.6.0
  injectable: ^2.3.0
  provider: ^6.1.5
  rxdart: 0.28.0
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  auto_route_generator: ^10.2.3
  injectable_generator: ^2.4.0


flutter:

  uses-material-design: true
  assets:
    - pubspec.yaml
    - assets/svg/
    - assets/image/